### ISSUE TITLE
add note/section on conflicts

### ISSUE THREAD

**Issue by autonome** [darobin/proto-handler-reqs#8]
> For instance, using this approach an extension could implement support for [IPFS](https://docs.ipfs.tech/concepts/what-is-ipfs/) directly within any browser context.

should pre-game the immediate "but what about conflicts?!" question that readers will have at this point.

**Comment by darobin** [comment]
Good point. I included a paragraph to discuss that. I'm not super happy with where it landed but I'm not sure how much better we can do. (I mean, the text can probably be better, but not sure about the modality.) The existing rPH already gives UAs a lot of leeway in how they handle registration (which is good). We can't take that away but it also doesn't constrain the space much. And a programmatic handler conflicting with a handoff handler could be really weird, it's hard to figure out what's intuitive.
